In [117]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/customer-call-dataset/Customer Call List.xlsx

In [118]:
import pandas as pd

In [119]:
df = pd.read_excel("/kaggle/input/customer-call-dataset/Customer Call List.xlsx")
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True
20,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [120]:
#removes duplicates
df = df.drop_duplicates()
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Not_Useful_Column
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No,True
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes,False
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN,True
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,True
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No,True
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes,True
6,1007,Jeff,Winger,NaN,1209 South Street,No,No,False
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No,False
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN,False
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No,True
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No,True
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN,True
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N,False
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No,False
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No,False
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N,False
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No,False
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN,True
18,1019,Creed,Braton,N/a,N/a,N/a,Yes,True
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N,True

In [121]:
#columns drop 
#df = df.drop(columns='Not_Useful_Column')
df = df.drop('Not_Useful_Column',axis=1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,/White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,...Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson_,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [122]:
df["Last_Name"] = df["Last_Name"].str.strip("123._/")
df["Last_Name"]
#"123._/" means that any leading occurrence of the characters 1, 2, 3, ., _, or / will be removed.
#3_abc", "/.123_def", "123./ghi", "_jkl
#0      abc
#1      def
#2      ghi
#3      jkl

0        Baggins
1          Nadir
2          White
3        Schrute
4           Snow
5        Swanson
6         Winger
7         Holmes
8            NaN
9         Parker
10        Gamgee
11        Potter
12        Draper
13         Knope
14    Flenderson
15       Weasley
16         Scott
17          Kent
18        Braton
19     Skywalker
Name: Last_Name, dtype: object

In [123]:
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123/643/9775,93 West Main Street,No,Yes
2,1003,Walter,White,7066950392,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876|678|3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,876|678|3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,N/a,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,7066950392,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876|678|3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123/643/9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,7066950392,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,N/a,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876|678|3469,"910 Tatooine Road, Tatooine",Yes,N

In [124]:
df['Phone_Number'] = df['Phone_Number'].str.replace('|','')
df['Phone_Number'] = df['Phone_Number'].str.replace('/','')
df['Phone_Number'] = df['Phone_Number'].str.replace('--','-')
df['Phone_Number'] = df['Phone_Number'].str.replace('nan-','')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na-','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-545-5421,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,1236439775,93 West Main Street,No,Yes
2,1003,Walter,White,NaN,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-543-2345,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,8766783469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-762-2467,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,NaN,1209 South Street,No,No
7,1008,Sherlock,Holmes,8766783469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-545-5421,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,NaN,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,NaN,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-543-2345,2039 Main Street,Yes,N
13,1014,Leslie,Knope,8766783469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-762-2467,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-545-5421,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,1236439775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,NaN,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na,N/a,N/a,Yes
19,1020,Anakin,Skywalker,8766783469,"910 Tatooine Road, Tatooine",Yes,N

In [125]:
def make(x):
    x = str(x)
    return x[0:3] + '-' + x[3:6] + '-' + x[6:10]

df['Phone_Number'] = df['Phone_Number'].apply(make)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123--54-5-54,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,nan--,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123--54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304--76-2-24,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,nan--,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,Na--,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123--54-5-54,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,nan--,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,nan--,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123--54-3-23,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304--76-2-24,214 HR Avenue,N,No
15,1016,Ron,Weasley,123--54-5-54,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,nan--,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,Na--,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [126]:
df['Phone_Number'] = df['Phone_Number'].str.replace('|','')
df['Phone_Number'] = df['Phone_Number'].str.replace('/','')
df['Phone_Number'] = df['Phone_Number'].str.replace('--','-')
df['Phone_Number'] = df['Phone_Number'].str.replace('nan-','')
df['Phone_Number'] = df['Phone_Number'].str.replace('Na-','')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact
0,1001,Frodo,Baggins,123-54-5-54,"123 Shire Lane, Shire",Yes,No
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes
2,1003,Walter,White,,298 Drugs Driveway,N,NaN
3,1004,Dwight,Schrute,123-54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No
5,1006,Ron,Swanson,304-76-2-24,768 City Parkway,Yes,Yes
6,1007,Jeff,Winger,,1209 South Street,No,No
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN
9,1010,Peter,Parker,123-54-5-54,"25th Main Street, New York",Yes,No
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN
12,1013,Don,Draper,123-54-3-23,2039 Main Street,Yes,N
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No
14,1015,Toby,Flenderson,304-76-2-24,214 HR Avenue,N,No
15,1016,Ron,Weasley,123-54-5-54,2395 Hogwarts Avenue,No,N
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN
18,1019,Creed,Braton,,N/a,N/a,Yes
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N

In [127]:
#splitting a column data based on comma
df[["Street","State","Zipcode"]] = df["Address"].str.split(",", n=2, expand=True)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Address,Paying Customer,Do_Not_Contact,Street,State,Zipcode
0,1001,Frodo,Baggins,123-54-5-54,"123 Shire Lane, Shire",Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,93 West Main Street,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,298 Drugs Driveway,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-54-3-23,"980 Paper Avenue, Pennsylvania, 18503",Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,123 Dragons Road,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-76-2-24,768 City Parkway,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,1209 South Street,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,98 Clue Drive,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,123 Middle Earth,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-54-5-54,"25th Main Street, New York",Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,"612 Shire Lane, Shire",Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,2394 Hogwarts Avenue,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-54-3-23,2039 Main Street,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,343 City Parkway,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-76-2-24,214 HR Avenue,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-54-5-54,2395 Hogwarts Avenue,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,"121 Paper Avenue, Pennsylvania",Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,3498 Super Lane,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,"910 Tatooine Road, Tatooine",Yes,N,910 Tatooine Road,Tatooine,None

In [128]:
df = df.drop('Address', axis=1)
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,State,Zipcode
0,1001,Frodo,Baggins,123-54-5-54,Yes,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,No,Yes,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-54-3-23,Yes,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-76-2-24,Yes,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,No,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Yes,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-54-5-54,Yes,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Yes,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-54-3-23,Yes,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Yes,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-76-2-24,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-54-5-54,No,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Yes,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Yes,N,910 Tatooine Road,Tatooine,None

In [129]:
df['Paying Customer'] = df['Paying Customer'].str.replace('Yes', 'Y')
df['Paying Customer'] = df['Paying Customer'].str.replace('No', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,State,Zipcode
0,1001,Frodo,Baggins,123-54-5-54,Y,No,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Yes,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-54-3-23,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,No,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-76-2-24,Y,Yes,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,No,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,No,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-54-5-54,Y,No,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,No,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-54-3-23,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,No,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-76-2-24,N,No,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-54-5-54,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,No,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Yes,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [130]:
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('Yes', 'Y')
df['Do_Not_Contact'] = df['Do_Not_Contact'].str.replace('No', 'N')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,State,Zipcode
0,1001,Frodo,Baggins,123-54-5-54,Y,N,123 Shire Lane,Shire,None
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,None,None
2,1003,Walter,White,,N,NaN,298 Drugs Driveway,None,None
3,1004,Dwight,Schrute,123-54-3-23,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,None,None
5,1006,Ron,Swanson,304-76-2-24,Y,Y,768 City Parkway,None,None
6,1007,Jeff,Winger,,N,N,1209 South Street,None,None
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,None,None
8,1009,Gandalf,NaN,,Y,NaN,123 Middle Earth,None,None
9,1010,Peter,Parker,123-54-5-54,Y,N,25th Main Street,New York,None
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,None
11,1012,Harry,Potter,,Y,NaN,2394 Hogwarts Avenue,None,None
12,1013,Don,Draper,123-54-3-23,Y,N,2039 Main Street,None,None
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,None,None
14,1015,Toby,Flenderson,304-76-2-24,N,N,214 HR Avenue,None,None
15,1016,Ron,Weasley,123-54-5-54,N,N,2395 Hogwarts Avenue,None,None
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,None
17,1018,Clark,Kent,,Y,NaN,3498 Super Lane,None,None
18,1019,Creed,Braton,,N/a,Y,N/a,None,None
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,None

In [132]:
df = df.fillna('')
df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,State,Zipcode
0,1001,Frodo,Baggins,123-54-5-54,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1003,Walter,White,,N,,298 Drugs Driveway,,
3,1004,Dwight,Schrute,123-54-3-23,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-76-2-24,Y,Y,768 City Parkway,,
6,1007,Jeff,Winger,,N,N,1209 South Street,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
8,1009,Gandalf,,,Y,,123 Middle Earth,,
9,1010,Peter,Parker,123-54-5-54,Y,N,25th Main Street,New York,
10,1011,Samwise,Gamgee,,Y,N,612 Shire Lane,Shire,
11,1012,Harry,Potter,,Y,,2394 Hogwarts Avenue,,
12,1013,Don,Draper,123-54-3-23,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-76-2-24,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-54-5-54,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
17,1018,Clark,Kent,,Y,,3498 Super Lane,,
18,1019,Creed,Braton,,N/a,Y,N/a,,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [138]:
for x in df.index:
    if df.loc[x, 'Phone_Number'] == '':
        df.drop(x, inplace=True)

df

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,State,Zipcode
0,1001,Frodo,Baggins,123-54-5-54,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
3,1004,Dwight,Schrute,123-54-3-23,Y,Y,980 Paper Avenue,Pennsylvania,18503
4,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
5,1006,Ron,Swanson,304-76-2-24,Y,Y,768 City Parkway,,
7,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
9,1010,Peter,Parker,123-54-5-54,Y,N,25th Main Street,New York,
12,1013,Don,Draper,123-54-3-23,Y,N,2039 Main Street,,
13,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
14,1015,Toby,Flenderson,304-76-2-24,N,N,214 HR Avenue,,
15,1016,Ron,Weasley,123-54-5-54,N,N,2395 Hogwarts Avenue,,
16,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
19,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,

In [139]:
df.reset_index(drop=True)

,CustomerID,First_Name,Last_Name,Phone_Number,Paying Customer,Do_Not_Contact,Street,State,Zipcode
0,1001,Frodo,Baggins,123-54-5-54,Y,N,123 Shire Lane,Shire,
1,1002,Abed,Nadir,123-643-9775,N,Y,93 West Main Street,,
2,1004,Dwight,Schrute,123-54-3-23,Y,Y,980 Paper Avenue,Pennsylvania,18503
3,1005,Jon,Snow,876-678-3469,Y,N,123 Dragons Road,,
4,1006,Ron,Swanson,304-76-2-24,Y,Y,768 City Parkway,,
5,1008,Sherlock,Holmes,876-678-3469,N,N,98 Clue Drive,,
6,1010,Peter,Parker,123-54-5-54,Y,N,25th Main Street,New York,
7,1013,Don,Draper,123-54-3-23,Y,N,2039 Main Street,,
8,1014,Leslie,Knope,876-678-3469,Y,N,343 City Parkway,,
9,1015,Toby,Flenderson,304-76-2-24,N,N,214 HR Avenue,,
10,1016,Ron,Weasley,123-54-5-54,N,N,2395 Hogwarts Avenue,,
11,1017,Michael,Scott,123-643-9775,Y,N,121 Paper Avenue,Pennsylvania,
12,1020,Anakin,Skywalker,876-678-3469,Y,N,910 Tatooine Road,Tatooine,